name: Check PR Fix Inventory Infrastucture Apps Bundler
on:
  push:
    tags:
      - "*.*.*"
    branches:
      - main
  pull_request:
    paths:
      - "fixinventoryappbundler/**"
      - ".github/**"

jobs:
  fixinventoryappbundler:
    name: "fixinventoryappbundler" # Do not rename without updating workflow defined in publish.yml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"

      - name: Restore dependency cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{runner.os}}-pip-${{hashFiles('./requirements.txt')}}
          restore-keys: |
            ${{runner.os}}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox wheel flake8 build twine black
          pip install --pre fixinventorylib

      - name: Run tests
        working-directory: ./
        run: tox

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: ./htmlcov/

      - name: Build a binary wheel and a source tarball
        working-directory: ./
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/

      - name: Publish distribution to PyPI
        if: github.ref_type == 'tag'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_FIXINVENTORYAPPBUNDLER }}
          packages-dir: ./dist/
